name: Update Plugin Version

on:
  push:
    paths:
      - "vendor/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow
        uses: Mattraks/delete-workflow-runs@v2.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 0
          keep_minimum_runs: 0

      - name: Checkout repo
        uses: actions/checkout@v4.1.1

      - name: Set current date env
        run: echo "CURRENT_DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Commit and push
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "feat: update of plugin version"

      - name: Update plugin versions
        run: sed -i "s/Version: .*/Version: ${{ env.CURRENT_DATE }}/" fraise-plugin-ip2region.php

      - name: Generate Changelog
        run:
          |
          echo "### Changelog" > ${{ github.workspace }}-CHANGELOG.txt
          echo "- ✨ Upgrade the plugin version to \`${{ env.CURRENT_DATE }}\`" >> ${{ github.workspace }}-CHANGELOG.txt
          echo "------" >> ${{ github.workspace }}-CHANGELOG.txt
          echo "### 变更日志" >> ${{ github.workspace }}-CHANGELOG.txt
          echo "- ✨ 升级插件版本到 \`${{ env.CURRENT_DATE }}\`" >> ${{ github.workspace }}-CHANGELOG.txt

      - name: Create zip file
        run: zip -rq fraise-plugin-ip2region.zip ./ -x "README*" ".gitignore" ".github/*" ".git/*"

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          name: ${{ env.CURRENT_DATE }}
          tag_name: ${{ env.CURRENT_DATE }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: fraise-plugin-ip2region.zip
